const selectors = {
  regionsButton: '.cmp-regions-popup__trl.pointer',
  regions: '.cmp-regions-list__region ',
  cities: '.cmp-regions-list__locality',
  container: '.carousel-v4__scroller',
  buttons: '.rt-tabs-nav-v2_item',
  noData: '.stub-callback',
  tariffs: '.carousel-v4 .scrollable-cards__item[data-loaded="true"]',
  tariffName: '.card-title',
  tariffsArrow: '.carousel-v4__button-right:not(.carousel-v4__button--hide)',
  cookieConfirm: '#cookie-notification .rt-button-md--is-block.rt-button.rt-button-with-ripple.rt-button-orange-border',
  oldPriceValue: '.rt-price-v3__old-val',
  priceValue: '.rt-price-v3__val',
  buttonText: '.rt-button',
  discountMarkText: '.card-badge',
  tvBoxBuy: '.rt-tariff-price--inline',
  info: '.rt-microtabs-cnt__item:not(.rt-microtabs-cnt__item--hidden)',
  goByArrow: '.rt-microtabs-nav__control:not(.d-none)',
  arrow: '.rt-microtabs-nav__control:not(.d-none):not([active-tab])',
  goByTitles: '.rt-microtabs-nav__item--left',
  offers: '.rt-tariff-option__info',
  offerName: '.rt-tariff-option__desc',
  offerText: '.rt-tariff-option__title',
  currentCity: '.nav__change-region.change-region',
  regionClickTarget: '.b-regions__group-expand',
  internetContainer: '.landing-form-wrap',
  internetButton: '.landing-form-card',
};

export default selectors;
